# Generated by Django 5.2.7 on 2025-10-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_artikel_created_at_artikel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
