# Generated by Django 5.2.7 on 2025-10-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_artikel_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
