# Generated by Django 5.2.7 on 2025-10-23 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0004_alter_artikel_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_artikels', to=settings.AUTH_USER_MODEL),
        ),
    ]
