# Generated by Django 5.2.7 on 2025-10-13 11:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gunung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('ketinggian', models.TextField()),
                ('provinsi', models.CharField(max_length=255)),
                ('foto', models.URLField(blank=True, null=True)),
                ('deksripsi', models.TextField()),
            ],
        ),
    ]
