# Generated by Django 5.2.7 on 2025-10-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_gunung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunung',
            name='ketinggian',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
