# Generated by Django 5.2.5 on 2025-10-23 10:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('explore_gunung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPendakian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('summit_reached', models.BooleanField(default=True)),
                ('team_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gunung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='explore_gunung.gunung')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
