# Generated by Django 5.2.5 on 2025-10-23 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logpendakian', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logpendakian',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_pendakian', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='logpendakian',
            index=models.Index(fields=['user', 'start_date'], name='logpendakia_user_id_a6c74a_idx'),
        ),
        migrations.AddIndex(
            model_name='logpendakian',
            index=models.Index(fields=['gunung'], name='logpendakia_gunung__bd0d09_idx'),
        ),
        migrations.AddConstraint(
            model_name='logpendakian',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date')), ('end_date__isnull', True), _connector='OR'), name='end_gte_start_or_null'),
        ),
        migrations.AddConstraint(
            model_name='logpendakian',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rating__gte', 1), ('rating__lte', 5)), ('rating__isnull', True), _connector='OR'), name='rating_1_5_or_null'),
        ),
        migrations.AddConstraint(
            model_name='logpendakian',
            constraint=models.UniqueConstraint(fields=('user', 'gunung', 'start_date'), name='uniq_user_gunung_start'),
        ),
    ]
